# Generated by Django 6.0.2 on 2026-03-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aiinsight',
            unique_together=set(),
        ),
    ]
